# Generated by Django 3.0.3 on 2020-02-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200209_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
