# Generated by Django 3.0.3 on 2020-02-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='q6',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q7',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q8',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q9',
            field=models.BooleanField(default='True'),
        ),
    ]
