# Generated by Django 3.0.3 on 2020-02-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200209_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q1',
            field=models.BooleanField(default='True', help_text='Does pineapple belong on pizza?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q2',
            field=models.BooleanField(default='True', help_text='Are hot dogs sandwiches?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q3',
            field=models.BooleanField(default='True', help_text='Are you a morning person?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q4',
            field=models.BooleanField(default='True', help_text='Is your background picture is a selfie?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q5',
            field=models.BooleanField(default='True', help_text='Did you sit in a different seat each day in class?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q6',
            field=models.BooleanField(default='True', help_text='Do you eat pizza crust first?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q7',
            field=models.BooleanField(default='True', help_text='Do you pour milk in before the cereal?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q8',
            field=models.BooleanField(default='True', help_text='Do you put Christmas decorations on right after Halloween?'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q9',
            field=models.BooleanField(default='True', help_text='Do you drink ice coffee even in freezing weather?'),
        ),
    ]
