# Generated by Django 3.0.3 on 2020-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200209_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Location', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Full Name', max_length=20),
        ),
    ]
