# Generated by Django 3.0.3 on 2020-02-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200209_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Max 500 charaters.', max_length=500),
        ),
    ]
