# Generated by Django 3.0.3 on 2020-02-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='q1',
        ),
        migrations.AddField(
            model_name='questions',
            name='IsAHotdogASandwich',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q2',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q3',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q4',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q5',
            field=models.BooleanField(default='True'),
        ),
    ]
